### ISSUE TITLE
Everyday period

### ISSUE THREAD

**Issue by danzelziggy** [awslabs/aws-instance-scheduler#10]
What's the best way to define everyday in weekday option in the create-period command?

Will "mon-sun" work? Or you need to create two period, 1 for weekday and 1 for weekend?

Thanks in advanced!

**Comment by arieleeuw** [comment]
mon-sun will work, but if it runs on any day you can simply specify the start/end time and omit the days. (in the new scheduler we only use days, there is no distinction between working days and weekends) In order to create a "daily" scheduler use:

# create daily period
scheduler-cli create-period  --stack <your-stack-name> --begintime 09:00 --endtime 18:00 --name <name-of-daily-period>

# create a schedule that uses the period
scheduler-cli create-schedule --stack <your-stack-name> --name <daily-schedule-name> --periods <name-of-daily-period> [--timezone <your-optional-time-zone>]

Now simply tag your instances using the name of the daily schedule

Hope this helps

**Comment by danzelziggy** [comment]
Thank you!
