### ISSUE TITLE
Issue while migrating the solution from instance-scheduler-2.2.2.0 to version v1.3.0

### ISSUE THREAD

**Issue by saikumar239** [awslabs/aws-instance-scheduler#140]
While updating the stack from 2.2.2.0 to 1.3, SchedulerConfigHelper resource is throwing error "Modifying service token is not allowed."
Upon checking the cloud trail, the issue is that the new template is looking for Lambda which is not existing.
errorMessage": "Function not found: arn:aws:lambda:eu-west-1:xxxx:function:xxxx-InstanceSchedulerMain", 
Name of the lambda function that was originally created is: arn:aws:lambda:eu-west-1:xxxx:function:xxxx-Main-K5F024WN5YYB

**Comment by knihit** [comment]
Hi

Thank you for reaching our. We are sorry that you are experiencing this issue. To help us reproduce the same issue, may I request if you can look at the CloudFormation templates's description section for version number. The version number descirbed above is incorrect due to an issue with release management on our side.

**Comment by saikumar239** [comment]
I am attaching the template that we have received
[old instance.txt](https://github.com/awslabs/aws-instance-scheduler/files/3972282/old.instance.txt)
 from AWS.
Regards,
Sai

**Comment by tapughose** [comment]
Thank you, @saikumar239. I went through your attached template. It seems like your template version is equivalent to v1.1. We had couple of more releases (v1.2, v1.3) after that. I could not able to reproduce the issue when I updated from v1.2 to v1.3. However, I was able to reproduce when I attempted to update from v1.1 to v1.3. As a work around, I was able to update from v1.1 to v1.3 through a chain actions: updating from v1.1 to v1.2, followed by updating from v1.2 to v1.3. I have attached all three versions of the [tempate](https://github.com/awslabs/aws-instance-scheduler/files/3974091/tempates.zip). Please let us know if that works for you.

**Comment by tapughose** [comment]
> I am attaching the template that we have received
> [old instance.txt](https://github.com/awslabs/aws-instance-scheduler/files/3972282/old.instance.txt)
> from AWS.

I have went through your template (v2.2.2.0) and compared with our template v1.1 (which is 2.2.2.0 if you check in the description). I found that they are not same, especially, for `AWS::Lambda::Permission` (SchedulerInvokePermission) resource. This will make your update fail. I would recommend to make fresh deployment by using most recent template.

**Comment by saikumar239** [comment]
Thanks for reply, the issue with redeploying the stack is that this solution was running from a couple of years and all the schedules and periods were been created in a DynamoDB table. Now we need to copy that data into newly created tables. Also, I need to find out what else changes would be required. Do you see any other way of upgrading? 
Please note that we were migrating the solution as Python runtime of 2.7 has been deprecated for Lambda

**Comment by tapughose** [comment]
Please use the attached [template](https://github.com/awslabs/aws-instance-scheduler/files/3979645/instance-scheduler-1-3-custom.template.zip) for updating your stack. The template is same as v1.3 except that resource name of  `Custom::ServiceSetup` is changed from `SchedulerConfigHelper` to `SchedulerConfigHelperV3`. The custom resource is using lambda function's `arn` as `ServiceToken`. Since `ServiceToken` of a custom resource cannot be updated, I renamed the resource name so that a new custom resource is created (older one will be deleted) during stack update.

**Comment by knihit** [comment]
Hi @saikumar239 if the template provided @tapughose works, please let us know, also if this issue can be closed.

**Comment by saikumar239** [comment]
I dint get time today to test this. I will do this tomorrow and will
provide an update.

Thanks,
Sai

**Comment by saikumar239** [comment]
I have updated the stack and all good now. The runtime of the lambda was updated to 3.7 without issue. 
Thanks for the quick fix.
