### ISSUE TITLE
Version 1.3 logging not writing to correct Logstream

### ISSUE THREAD

**Issue by cgol** [awslabs/aws-instance-scheduler#147]
Logging output in CloudWatch logs from the Instance Scheduler v1.3 appears to have broken in that it is not writing to a descriptive account-date logstream like the previous version.

Instead there is an error being consistently written:
`Error writing to logstream Scheduler-ec2-123456789012-ap-southeast-2-20200204 with token None ('ClientError' object has no attribute 'message')
`
I suspect this might be masking a real error, and can't see the cause of the exception being thrown.  
With a large number of accounts, this makes it slow/time consuming to search for a problem in a particular account without the logstreams.

My knowledge of python is not sufficient to be able to solve this, so hoping you can provide a fix in the next version.

**Comment by ericquinones** [comment]
Hi @cgol 
Apologies for the issue you're experiencing. To help us troubleshoot, can you please let us know if you were previously on `v1.2` or an older version?

**Comment by lovepurohit** [comment]
Hi @cgol 
The issue that you are facing might be due to the conversion of instance scheduler from python 2 to python 3. There are some issues in the python3 code of instance scheduler for the exception or when it handles a request.
For more information, you can go through the below issue,

[https://github.com/awslabs/aws-instance-scheduler/issues/133]

**Comment by cgol** [comment]
Hi @lovepurohit Yes, that appears to be the same issue, I think this is therefore a duplicate and can be closed.
Thanks very much for your work in diagnosing the cause of the issue.
