### ISSUE TITLE
0 EC2 Instances discovered, but all our RDS instances are

### ISSUE THREAD

**Issue by mattlawnz** [awslabs/aws-instance-scheduler#156]
HI

After deploying the CF template, I can see in the logs, that our RDS instances are being discovered ok, but the EC2 Instances are not: really not sure what to check, here are the logs:

```

02:30:32
2020-03-26 - 02:30:32.564 - INFO : Handler SchedulerRequestHandler scheduling request for service(s) ec2, account(s) 3971******, region(s) ap-southeast-2 at 2020-03-26 02:30:32.564434

02:30:32
2020-03-26 - 02:30:32.784 - INFO : Running EC2 scheduler for account 3971****** in region(s) ap-southeast-2

02:30:33
2020-03-26 - 02:30:33.345 - INFO : Fetching ec2 instances for account 3971****** in region ap-southeast-2

02:30:42
2020-03-26 - 02:30:42.906 - INFO : Number of fetched ec2 instances is 0, number of instances in a schedulable state is 0
2020-03-26 - 02:30:42.906 - INFO    : Number of fetched ec2 instances is 0, number of instances in a schedulable state is 0

02:30:42
2020-03-26 - 02:30:42.964 - INFO : Scheduler result {'3971******': {'started': {}, 'stopped': {}, 'resized': {}}}

```

**Comment by knihit** [comment]
Hi @mattlawnz . Thank you for reaching out, sorry you faced this issue. We released a new version two weeks back (1.3.1) which has a fix for RDS instances. Can you please confirm the version you are using, so that we know if users are still facing this issue.

**Comment by mattlawnz** [comment]
Hi

we are currently using 1.3.1
```(SO0030) - aws-instance-scheduler, version v1.3.1```

**Comment by knihit** [comment]
Hi @mattlawnz , thanks for the clarification. Would you also provide some information about the schedule that you have setup for RDS & EC2. Also what tags are you using for both. Are they tagged the same key pair values.

**Comment by mattlawnz** [comment]
HI
we are using the tag called "hours_of_operation"
It was all pretty standard in terms to deployment - here are all of the variables:

Its wierd that its picking up 0 EC2 instances to analyse. So this isnt a case of not actually shutting down or starting up, its a case of not seeing any EC2 instances (and we have over 50
In the RDs logs we see that it picks all of the DB's to analyse, but none get scheduled, as we dont have the tags set yet for any of them

This is all in one account as well.
One other things the cloudformation got deployed to us-east-1, all our instances are in ap-southeast-2. This shouldnt matter should it?


```
CreateRdsSnapshot | Yes | -
-- | -- | --
CrossAccountRoles | - | -
DefaultTimezone | Pacific/Auckland | -
LogRetentionDays | 30 | -
MemorySize | 128 | -
Regions | ap-southeast-2 | -
ScheduleLambdaAccount | Yes | -
ScheduleRdsClusters | No | -
ScheduledServices | Both | -
SchedulerFrequency | 5 | -
SchedulingActive | Yes | -
SendAnonymousData | Yes | -
StartedTags | ScheduleMessage=Started on {day}/{month}/{year} at {hour}:{minute} {timezone} | -
StoppedTags | ScheduleMessage=Stopped on {day}/{month}/{year} at {hour}:{minute} {timezone} | -
TagName | hours_of_operation | -
Trace | Yes | -
UseCloudWatchMetrics | Yes
```

**Comment by tommyziegler** [comment]
Hi I am facing the similar issue,

trying to configure the Instance Scheduler, but the current version 1.3.1 doesn't find any instances. But I was facing the same issue with the earlier version 1.2.0, as I tried these one too.

```
2020-03-31 - 07:55:04.198 - INFO    : Handler SchedulerRequestHandler scheduling request for service(s) ec2, account(s) 402590864457, region(s) eu-central-1 at 2020-03-31 07:55:04.198533
2020-03-31 - 07:55:04.419 - INFO    : Running EC2 scheduler for account 402590864457 in region(s) eu-central-1
2020-03-31 - 07:55:05.387 - INFO    : Fetching ec2 instances for account 402590864457 in region eu-central-1
2020-03-31 - 07:55:05.376 - INFO    : Number of fetched ec2 instances is 0, number of instances in a schedulable state is 0
2020-03-31 - 07:55:05.376 - INFO    : Scheduler result {'402590864457': {'started': {}, 'stopped': {}, 'resized': {}}}
```

Following scenario:

- 1x EC2 Windows 2019 Instance (without encrypted EBS volume) in eu-central-1
- 1x RDS PostgreSQL Instance (with Storage encryption) in eu-central-1

Following is in my DynamoDB ConfigTable:

type (S) | name (S) | description (S) | use_metrics (BOOL) | begintime (S) | create_rds_snapshot (BOOL) | default_timezone (S) | endtime (S) | enforced (BOOL) | hibernate (BOOL) | periods (SS) | regions (SS) | retain_running (BOOL) | schedule_clusters (BOOL) | schedule_lambda_account (BOOL) | scheduled_services (SS) | started_tags (S) | stop_new_instances (BOOL) | stopped_tags (S) | tagname (S) | timezone (S) | trace (BOOL) | use_maintenance_window (BOOL) | weekdays (SS)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
config | scheduler | Instance-Scheduler for EC2 and RDS instances | FALSE |   | FALSE | UTC |   |   |   |   | { "eu-central-1" } |   | FALSE | TRUE | { "ec2", "rds" } | started-by=instance-scheduler |   | stopped-by=instance-scheduler | InstanceScheduler |   | TRUE |   |  
period | office-hours | Working-hours from 06:00 till 16:00 |   | 06:00 |   |   | 16:00 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | { "mon-fri" }
schedule | de-office-hours | pitKOMMUNAL Working-hours (German timezone) | FALSE |   |   |   |   | TRUE | FALSE | { "office-hours" } |   | FALSE |   |   |   |   | TRUE |   |   | Europe/Berlin |   | FALSE |  

On the EC-2 and RDS instance is configured the Scheduler Tag (`Schedule=de-office-hours`)
<img width="1158" alt="EC2_Tag" src="https://user-images.githubusercontent.com/1038755/78014021-9c471d80-7347-11ea-8d06-bea918633160.png">

My Instances won't stop or start. I tried already several things. As I understood from the documentation, the instance need to be stopped? For adding them, right? What is when the **enforced** Property is set for the schedule to true? The RDS instance maybe won't start in my case because of the Storage encryption, do I need there similar the kms:CreateGrant permission like for EBS volumes?

Additional, I tried out several things in creating the period and schedule also by schedule-cli. What I for example found out is that the hibernate, enforce, retain_running and stop_new_instances bool properties are defined in compare to the default schedule entries. Could that behave differently?

And when I check the DynamoDB StateTable database there is no entry created, doesn't matter if I use the CLI, the lambda function runs and find RDS instances etc. Could you maybe clarify when this table is written in?

Ah, and we also tried to do all the things with our AWS Root-user account. 

I think I have tried already many things, and I am giving now up. Would be good to hear back what you would need from me to find out what's the issue.

Many thanks
Tommy

**Comment by lovepurohit** [comment]
Hi @tommyziegler 
If your EBS volumes are encrypted then you will need to provide the km:CreateGrant permission to the role. Otherwise, it won't be able to start your instance.

Thank you

**Comment by lovepurohit** [comment]
Hi @mattlawnz 
Can you please check whether the role has sufficient permission to fetch the EC2 resources?
Also, verify that there is no account level deny policies which are stopping the lambda to fetching the resources.

If nothing, works, I would request you to redeploy the stack and see if that works.

Thank you

**Comment by mattlawnz** [comment]
HI
Ive tried redeploying, without success (same issue) Im unsure as to what to check with regard to the permissions

**Comment by gockle** [comment]
@mattlawnz Has this issue been resolved, if not can you confirm if the tags have been properly applied to the EC2 instances that are not being discovered. Please make sure they have same case as well.

**Comment by mattlawnz** [comment]
Hi @gockle 
you are right. It was the tags and case that was the problem. Thanks for your assistance!
