### ISSUE TITLE
Start/stop an instance in a specific day in week. Other days, instances are full running.

### ISSUE THREAD

**Issue by hoa89nguyen** [awslabs/aws-instance-scheduler#180]
Do we have any way to set start time and end time of ECs for specific day in every week and keep other days in that week the EC2s are fully running.
Example: In Tuesday every week, we want to stop the ECs at 6:00 AM, and start them again at 6:00 PM. The rest of days in week the ECs are fully running.
I tried many ways from creating single period to multiple periods, however it's not as expected. It seems the document in AWS doesn't specify much information to fulfill for this case.
 In the latest way, I created 3 periods but it also doesn't restart the servers as expected.
Full time:
![image](https://user-images.githubusercontent.com/8321686/86777903-f280d680-c083-11ea-8096-fafa56d04d77.png)
Stopping time:
![image](https://user-images.githubusercontent.com/8321686/86778255-5d321200-c084-11ea-8f33-8a26debf2d10.png)
 Starting time:
![image](https://user-images.githubusercontent.com/8321686/86778196-468bbb00-c084-11ea-85f8-ec22cf9a6ef7.png)
Could you please advise me any way to fulfill my request above?

Thanks

**Comment by praveenis** [comment]
Hi @hoa89nguyen , Currently we are not supporting the schedule which have an end time earlier than a begin time for the same day. however we can make this work by identifying a timezone where start time and end time falls in different days . For  your scenario, you can use timezone UTC -7 or UTC +7 hours in your schedule so that you can create 3 different period with different days.

For e.g If you use timezone: US/Mountain (UTC -7 hours) in schedule
Mon 18:00 begintime in UTC will be Mon 11:00 - Period 1 
Tue to Sat - Period 2
Mon 6:00 endtime in UTC will be Sun 23:00 - Period 3

Please let us know if this works for you. 

Thanks,
Praveen
