### ISSUE TITLE
Instance Tagging Syntax Documentaiton

### ISSUE THREAD

**Issue by mikedizzle** [awslabs/aws-instance-scheduler#3]
In previous versions of the scheduler, there were tagging examples and syntax breakdown. That seems to be missing from this version's documentation.

**Comment by AmangPulo** [comment]
I also would like to know how to make custom schedule and tags on the instances.

**Comment by arieleeuw** [comment]
Instances are now tagged with names of **Schedules** which consist of one or more **Periods**. A period defines the times and dates on which instances are running. One or more periods are then combined with an optional timezone and other options into a Scheduler. Both Schedules and Periods are defined in the InstanceScheduler-Config-<suffix> table that is created as part of the stack that deploys the solution. For rows that define a period the name attribute of the row must be set to "period", for schedules this is "schedule". Attributes that can be used are described in the Implementers Guide https://docs.aws.amazon.com/solutions/latest/instance-scheduler/components.html.  The table comes with a set of example periods and schedules that can be customised or used as starting point for your own periods and schedules.

Instead of modifying the table directly it is also possible to use the scheduler-cli. This CLI is described at https://docs.aws.amazon.com/solutions/latest/instance-scheduler/appendix-a.html and lists all possible actions and parameter to manage periods and schedules.

Below are some examples that show how to describe how to describe and create new periods and schedules

# show all schedules
scheduler-cli.py describe-schedules --stack <scheduler stack name>

# show all periods
python scheduler-cli.py describe-periods --stack <scheduler stack name>

#show single schedule
python scheduler-cli.py describe-schedules --stack <scheduler stack name> --name uk-office-hours

# show single period
python scheduler-cli.py describe-periods --stack <scheduler stack name> --name office-hours

#show start/stopped schedules
python scheduler-cli.py describe-schedules --stack <scheduler stack name> --name running
python scheduler-cli.py describe-schedules --stack <scheduler stack name> --name stopped

# show multiple periods with scaling
python scheduler-cli.py describe-schedules --stack <scheduler stack name> --name scale-up-down

#show more complex period
python scheduler-cli.py describe-periods --stack <scheduler stack name> --name first-monday-in-quarter

# show usage for today
python scheduler-cli.py describe-schedule-usage --stack <scheduler stack name> --name uk-office-hours 

# for a week
python scheduler-cli.py describe-schedule-usage --stack <scheduler stack name> --name uk-office-hours --startdate 20170731 --enddate 20170806

# create a periods
python scheduler-cli.py create-period --stack <scheduler stack name> --name week --weekdays mon-fri --begintime 09:00 --endtime 18:00

python scheduler-cli.py create-period --stack <scheduler stack name> --name weekend --weekdays sat-sun --begintime 10:00 --endtime 16:00

#create schedule with local timezone
python scheduler-cli.py create-schedule --stack <scheduler stack name> --name nl-office-hours --periods week,weekend --timezone Europe/Amsterdam

# show usage
python scheduler-cli.py describe-schedule-usage --stack <scheduler stack name> --name nl-office-hours

**Comment by shsenior** [comment]
Closing due to time elapsed since last correspondence. Please re-open this if you are still having an issue.
