### ISSUE TITLE
Any performance issues with instances of about ~1500 across N different accounts

### ISSUE THREAD

**Issue by prateek121** [awslabs/aws-instance-scheduler#46]
Can you let me know design consideration If we have 40 odd accounts and 1500 instances in all (EC2+RDS)  running from a single account with cross account role assumption ?

- Memory to be increased.
- Time limit to be lambda max (5mins)
- Any other ??
- Will there parallel invocation of lambda for each account or single invocation does the job ?

**Comment by arieleeuw** [comment]
Hi,
In order to make this scalable we will execute a separate lambda function for each account/region/service combination from the main scheduler. So if you have 40 accounts for which you want to schedule EC2 and RDS instances we will start execute 80 Lambda instance per region. EC2 instances are started in batches of 5, and stopped in Batches of 50. 
The limit is how many of start/stop calls we can make within the minutes for each Lambda (including the delays in case calls get throttled) 
If you have many instances in a single account/region I recommend to increase the size of the lambda function to avoid timeouts selecting and starting/stopping these instances.
Hopes this help
Arie

**Comment by prateek121** [comment]
Thanks @arieleeuw ,appreciate your quick response.

**Comment by shsenior** [comment]
Closing due to time elapsed since last correspondence. Please re-open this if you are still having an issue.
