### ISSUE TITLE
Support for EC2 hibernation

### ISSUE THREAD

**Issue by JoostSaanen** [awslabs/aws-instance-scheduler#56]
With the recent announcement of [EC2 Hibernation](https://aws.amazon.com/blogs/aws/new-hibernate-your-ec2-instances/), I was wondering if there a plans to update the Instance Scheduler for supporting this.

**Comment by arieleeuw** [comment]
Hi Joost,

We've finished the code to support hibernation this week. 
There will be a new option "hibernate" that can be to true at schedule level.

All instances that use this schedule will be hibernated at the end of a running period. If hibernation fails, because the EC2 instance does not meet the requirements for hibernation, or is stopped for resizing, it will be stopped without hibernation.

We also have added support for RDS Multi-AZ instances and Aurora clusters.

This all will be part of our upcoming maintenance release.

Regards,
Arie

**Comment by youwalther65** [comment]
I would appreciate this information as well because we are waiting for using AWS Instance Scheduler for Multi AZ and Aurora as well! Thx in advance!

**Comment by shsenior** [comment]
Fixed in v1.2.0
