### ISSUE TITLE
Enable Maintenance window option for "Instance scheduler" and understand its behavior. 

### ISSUE THREAD

**Issue by krishnaCNagalla** [awslabs/aws-instance-scheduler#57]
Hi,

I wanted to enable Maintenance Window option for Instance Scheduler. 
1) Can you help me with the API for this. "use_maintenance_window" used as an attribute in the custom service ('Custom::ServiceInstanceSchedule') properties giving error. Please correct me with the correct attribute.
ex: 
OfficeChicagoTimeZone7PMto7AM:
    Type: 'Custom::ServiceInstanceSchedule'
    Properties:
      Description: Working Hours in Chicago
      ServiceToken: >-
        ****************************************************************************_main
      Enforced: 'False'
      Timezone: America/Chicago
      use_maintenance_window: 'True'
      Periods:
        - Description: Hours in weekdays and weekends
          BeginTime: '07:00'
          EndTime: '19:00'
          WeekDays: Mon-Sun

2) What if the maintenance for the RDS instances goes beyond the Maintenance Window time.  Will the scheduler wait until the Maintenance is complete or will it stops the instance based on the timings of the maintenance window.

**Comment by arieleeuw** [comment]
Hi,

The name for this property is "UseMaintenanceWindow" 

Below is a list off all properties (including the ones for our upcoming 1.2 update)

```
PROP_BEGIN_TIME = "BeginTime"
PROP_DESCRIPTION = "Description"
PROP_END_TIME = "EndTime"
PROP_ENFORCED = "Enforced"
PROP_HIBERNATE = "Hibernate"
PROP_RETAIN_RUNNING = "RetainRunning"
PROP_INSTANCE_TYPE = "InstanceType"
PROP_METRICS = "Metrics"
PROP_MONTH_DAYS = "MonthDays"
PROP_MONTHS = "Months"
PROP_OVERRIDE_STATUS = "OverrideStatus"
PROP_OVERWRITE = "Overwrite"
PROP_PERIODS = "Periods"
PROP_STACK_NAME = "SchedulerStack"
PROP_NO_STACK_PREFIX = "NoStackPrefix"
PROP_STOP_NEW = "StopNewInstances"
PROP_TIMEZONE = "Timezone"
PROP_USE_MAINTENANCE_WINDOW = "UseMaintenanceWindow"
PROP_WEEKDAYS = "WeekDays"
```

If the maintenance take longer we won't stop the instance until maintenance is done. When we select the instances for scheduling filter on instances that are in a running or stopped state.

Hope this helps, feel free to reach out if you need more help. 

regards,
Arie

**Comment by krishnaCNagalla** [comment]
Hi, 

Thank you so much for the quick response. 
I tried using "UseMaintenanceWindow" and update the stack but it is giving an error instead. Please see below. Can you please correct if I am wrong or help me with the error? 

Schedule:

OfflineChicagoTimeZone7PMto7AM:
    Type: 'Custom::ServiceInstanceSchedule'
    Properties:
      Description: Working Hours in Chicago
      ServiceToken: >-
        arn:aws:lambda:us-east-1:901705342470:function:aws_usf_lambda_sre_instancescheduler_main
      Enforced: 'False'
      UseMaintenanceWindow: 'True'
      Timezone: America/Chicago
      Periods:
        - Description: Hours in weekdays and weekends
          BeginTime: '07:00'
          EndTime: '19:00'
          WeekDays: Mon-Sun

![image](https://user-images.githubusercontent.com/42155949/49820647-1bbd7180-fd3e-11e8-8e26-dbcad4145231.png)

**Comment by arieleeuw** [comment]
Hi,

Looking at it I think the name of the service token is incorrect ( "_" instead of "-" in name of the Lambda)


can you please try the following template after setting your account and region?

```
AWSTemplateFormatVersion: 2010-09-09
Description: ''
Resources:
  Chicago7AMto7PM:
    Type: 'Custom::ServiceInstanceSchedule'
    Properties:
      ServiceToken: >-
        arn:aws:lambda:<REGION>:<ACCOUNT>:function:<STACKNAME>-InstanceSchedulerMain
      UseMaintenanceWindow: 'True'
      Enforced: 'false'
      Timezone: America/Chicago
      Periods:
        - BeginTime: '07:00'
          EndTime: '17:00'
          WeekDays: Mon-Sun
```

If I'm deploying this stack it creates the following Schedule:

```
scheduler-cli describe-schedules --stack InstanceScheduler --name TESTSTACK-Chicago7AMto7PM
{
   "Schedules": [
      {
         "RetainRunning": false, 
         "Enforced": false, 
         "Hibernate": false, 
         "Name": "TESTSTACK-Chicago7AMto7PM", 
         "ConfiguredInStack": "arn:aws:cloudformation:*******:stack/TESTSTACK/*******", 
         "StopNewInstances": true, 
         "Periods": [
            "TESTSTACK-Chicago7AMto7PM-period-0001"
         ], 
         "UseMaintenanceWindow": true, 
         "Timezone": "America/Chicago", 
         "Type": "schedule"
      }
   ]
}
```

If you still have errors please look in the ScheduleResourceHandler-yyyymmdd log stream that contains all detailed information how the cistom resource request is handled.

**Comment by krishnaCNagalla** [comment]
Hi, 

-The name of the service token is working fine before inclidingyt the "UseMaintenanceWindow" property. It is in use for quite some time and now I wanted to include this property to the existing stack. 

-But, I figured out that there is a typo in the property name ("UseMaintenaceWindow" instead of "UseMaintenanceWindow") from one your other threads. (https://github.com/awslabs/aws-instance-scheduler/issues/34)
-Stack update was successful with "UseMaintenaceWindow".
-But when I was testing on an RDS instance, it is responding for the start and stop schedule perfectly and it was in a stop state, but the scheduler didn't start the instance as per the maintenance window timings. Not sure if I am missing some thing.

**Comment by arieleeuw** [comment]
The best way to find out why/when instances are, or aren't, started/stopped is by enabling the trace option in the main stack. The scheduler will then log all steps of evaluating the periods in a schedule in the logstream for that service/account/region.

If you have any difficulties or want to understand the logic of your schedules, please let's have a look at the content of the logstream


On 11 Dec 2018, at 20:04, krishnaCNagalla <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

-The name of the service token is working fine before inclidingyt the "UseMaintenanceWindow" property. It is in use for quite some time and now I wanted to include this property to the existing stack.

-But, I figured out that there is a typo in the property name ("UseMaintenaceWindow" instead of "UseMaintenanceWindow") from one your other threads. (#34<https://github.com/awslabs/aws-instance-scheduler/issues/34>)
-Stack update was successful with "UseMaintenaceWindow".
-But when I was testing on an RDS instance, it is responding for the start and stop schedule perfectly and it was in a stop state, but the scheduler didn't start the instance as per the maintenance window timings. Not sure if I am missing some thing.

**Comment by shsenior** [comment]
Closing due to time elapsed since last correspondence. Please re-open this if you are still having an issue.
