### ISSUE TITLE
Potential integration with AWS Systems Manager?

### ISSUE THREAD

**Issue by nebffa** [awslabs/aws-instance-scheduler#58]
Hey there,

I really like this solution. 

I have a question re: AWS Systems Manager Maintenance Windows. At my current company, we use SSM to take care of Operating System Patching, and we'd like servers to be on for the duration of the SSM Maintenance Windows without us having to make sure the instance scheduler windows include the SSM Maintenance Windows intervals. Are there any plans to make this solution aware of SSM Maintenance Windows?

**Comment by arieleeuw** [comment]
Will this work for you?

For RDS instances we already have an use_maintenance_window option that can be set to use the RDS preferred maintenance windows as a running period. For EC2 instances we can add an additional ssm_maintenance_window option at schedule level to specify a name of an SSM maintenance window. If this and options is set and the use_maintenance_window option is set to True, then a dynamic schedule will be added which EC2 instances will be running. The start time of for the instances is the start time of the next execution of the ssm maintenance period, minus the scheduling interval of the scheduler, or at least 10 minutes, in order to let the instances become available before the start of the maintenance window.
The end time is the execution time of the next execution of the ssm maintenance window plus the duration of the window.

**Comment by nebffa** [comment]
Sorry for being so slow to respond. Yes, that would work really well! Being able to associate a schedule with one maintenance window would work well for our needs.

**Comment by shsenior** [comment]
Fixed in v1.2.0
