### ISSUE TITLE
what is required to make this work, if the lambda is attached to a VPC and sit behind a security group?

### ISSUE THREAD

**Issue by ziyadmhd** [awslabs/aws-instance-scheduler#69]
We have our org security policy that requires the lambda to be attached to a VPC and behind a security group. it doesn't work when i do so, not even in the same account. What ports or routes need update if i were to make these network changes to lambda ?

**Comment by arieleeuw** [comment]
We did not design or test the lambda to work in a VPC.

In order to make it work you have to setup the routing table in so that the Lambda has internet access through a NAT Gateway,  Internet Gateway or VPC endpoint to the following services endpoints.

For a full list of the accessed services open the InstanceScheduler -SchedulerRole and check the SchedulerPolicy

(https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints.html)

- DynamoDB
- SNS
- Lambda
- CloudWatch
- CloudWatch Logs
- EC2
- RDS
- Secure Token Service
- Resource Groups Tagging API

in next update

- SSM

**Comment by ziyadmhd** [comment]
thank you, i have figured this out. i put this in a private subnet with a NAT and attached a security group with outbound on port 443.
