### ISSUE TITLE
Consider using functools.reduce instead of implementing your own _reduce()

### ISSUE THREAD

**Issue by ilyash-b** [awslabs/aws-instance-scheduler#81]
`source/code/configuration/instance_schedule.py` implements _reduce()

According to https://docs.python.org/3.0/whatsnew/3.0.html#builtins , one should use `functools.reduce` instead.

**Comment by arieleeuw** [comment]
As this code is currently designed for Python 2 we decided to go for this lightweight version independent implementation

**Comment by ilyash-b** [comment]
I'm 90% sure `functools.reduce` works in Python 2

**Comment by arieleeuw** [comment]
the 8 lines of Python we used to get the similar functionality work  100% in Python2 and reduce the footprint of another library and any version dependencies

**Comment by ilyash-b** [comment]
functools.reduce is part of standard library since 2.6

If you need to support earlier versions, dismiss the issue.

If 2.6+ is OK for you, you definitely should use functools.reduce and stop copy+pasting between projects.

**Comment by arieleeuw** [comment]
Thanks for your feedback. As mentioned before, we preferred to have the 8 lines of code rather than having the footprint of another library, as the code is only used internally in a single method and is not meant as a replacement for the reduce function in general.  If you think functool works better for you you can always fork the repository and use this library

**Comment by ilyash-b** [comment]
> footprint of another library

Irrelevant argument because it's standard library, as I mentioned: "functools.reduce is part of standard library since 2.6"

**Comment by arieleeuw** [comment]
Thanks for for feedback, we’ll consider it for future development
