### ISSUE TITLE
Instances not being stopped correctly

### ISSUE THREAD

**Issue by electric** [awslabs/aws-instance-scheduler#9]
I'm seeing some pretty odd behaviour with my EC2 scheduler. My first thought is that it's because I'm trying to schedule OpsWorks EC2 instances, as the RDS schedule is working fine.

Below are logs showing the desired state is stopped, and that the Scheduler is not stopping the instances.

`2018-02-18 - 06:00:23.248 - DEBUG : No running periods at this time found in schedule "instance-schedule-opsworks" for this time, desired state is stopped
2018-02-18 - 06:00:23.248 - DEBUG : Desired state for instance from schedule "instance-schedule-opsworks" is stopped, last desired state was stopped, actual state is running
2018-02-18 - 06:00:23.248 - INFO : Scheduler result {'752691938387': {'started': {}, 'resized': {}, 'stopped': {}}}`

**Comment by arieleeuw** [comment]
Hi,

By default will compare the **last desired state** with the **desired state** based on the schedule. As the last registered desired state in this case is "stopped" and so is the desired state the scheduler will not issue a stop command to the server even is the **actual state** is "running" As the new desired state based on the schedule differs from the last desired state then the scheduler will issue a start/stop command to the instance to bring the instance in the desired state and register this as the last desired state. This logic of comparing the registered last desired state with the desired state, instead of the actual instance state, is  used to let the schedule honour the state of instances manually start/stop instances by the users.
In your situation the scheduler has set the last desired state to stopped, in which case matched with the state for that moment in the "instance-schedule-opsworks" schedule, so we do not stop the instance. The instance might have been started manually or by the OpsWorks stack. When this schedule enters a period, in which the instance must be running, it will register the desired running state but as the instance s already running it will not need to start the instance. Only when the desired state at the end of the period goes to "stopped" (which is different from the registered) last desired state the scheduler will stop the instance.
So in normal operations, not the actual server state, but the registered last desired state for the instance is used. If you want to enforce the desired state from a schedule, then you can set the enforced flag on a schedule, in which case the actual state of the instance is used instead of the last desired state. This means that instances that are manually stopped in a running period will be started by the scheduler, and instances that are started outside of a running period will be stopped. 
As instances that are part of an OpsWorks stack are managed by that stack I recommend to mange the state of these instances through the OpsWorks stack.

**Comment by electric** [comment]
Thank you for this - that makes sense.

I guess with your suggestion, ideally there would be an "OpsWorks" scheduler that could manage those resources, rather than doing it through EC2. Is this something that is likely to come at a future time?

**Comment by arieleeuw** [comment]
Need to look into this as OpsWorks already has a great scheduling option for time based instances

**Comment by electric** [comment]
Cool thank you - time-based instances are a good workaround for now. I think it's safe to close this issue now.

**Comment by jeffmacd99** [comment]
Hello,
I am also trying to implement this scheduler and am having some issues, basically it will not start the instance as per the schedule. All the logs indicate that it should start and the scheduler says it's starting the instance and actually logs that it has started but the instance never starts. 


2018-04-03 - 14:15:32.275 - DEBUG : Desired state for instance from schedule "seattle-office-hours" is running, last desired state was stopped, actual state is stopped
2018-04-03 - 14:15:32.277 - DEBUG : Listing instance EC2:i-0df2abxxxxxx (instance16.west.aws) in region us-west-2 with instance type m4.2xlarge to be started by scheduler
2018-04-03 - 14:15:32.280 - INFO : Starting instances EC2:i-0df2abxxxxxx3 (instance16.west.aws) in region us-west-2
2018-04-03 - 14:15:32.674 - INFO : Scheduler result {'xxxxxxxxx': {'started': {u'us-west-2': [{'i-0df2abxxxxx': {'schedule': 'seattle-office-hours'}}]}, 'resized': {}, 'stopped': {}}}

The CloudTrail logs all show this start attempt by the scheduler

  "responseElements": {
        "requestId": "941511fa-f232-44e2-b343-a75d3fb89904",
        "instancesSet": {
            "items": [
                {
                    "instanceId": "i-0df2ab2xxxxxx",
                    "currentState": {
                        "code": 0,
                        "name": "pending"
                    },
                    "previousState": {
                        "code": 80,
                        "name": "stopped"

The scheduler does actually stop the instances according to the schedule, just will not start.

What am I missing here?
Thanks

**Comment by arieleeuw** [comment]
Hi,
Thanks for your detailed info.
According to the last part of the log the the scheduler has made a successful to the EC2 API to start it again as it is moved from a "stopped" into to a "pending" state and waiting for your reservation request to be full filled (allocating a host)  If the instance stays within this state please stop and start it from the console. If this problem continues then we need to check with EC2 support why this instance is not coming back into a running state. Is the instance part of any auto scaling group or ECS cluster?

**Comment by jeffmacd99** [comment]
Thanks you for your reply. This instance is not part of a ASG or ECS cluster. Other than the message in the CloudTrail log I never actually see it in a 'pending' state. At least the console never show that, it just remains in a stopped state

**Comment by jeffmacd99** [comment]
Hello, I believe I found the issue with instance startup. My EBS volumes are encrypted, I added "kms:CreateGrant" to the instanceSchduler role and now the instances are starting as per the schedule

**Comment by arieleeuw** [comment]
Thanks for reporting this back to us. I'll ask the techwriters to include this in the documentation

**Comment by rogerwatson** [comment]
The "kms:CreateGrant" fixes our issues with launching also, had been completely bamboozled for 12 days!! Thank you!

**Comment by C-Kenny** [comment]
Adding "kms:CreateGrant" to the role resolved this for us also, when the Instance Scheduler is dealing with encrypted volumes.

We could see StartInstances calls in CloudTrail but no StopInstances that would indicate why the instance would be in a Stopped state.

**Comment by arieleeuw** [comment]
We've document this in the implementers guide. For security reasons we did not add this permission by default to the template

**Comment by shsenior** [comment]
Fixed in v1.2.0
